# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Victory Square Block Party
email: technicalmanager@citr.ca
description: >- # this means to ignore newlines until "baseurl:"
  Hosted annually by Music Waste Festival, CiTR 101.9FM and Discorder Magazine, 
  the block party highlights local, independent music in a free end-of-summer 
  celebration that also supports local non-profit and independent media organizations.
baseurl: "/victory-square-block-party" # the subpath of your site, e.g. /blog
url: "https://saw-mon-and-natalie.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: sw0nt
github_username:  Saw-mon-and-Natalie

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# sass build settings
sass:
  style: :compressed
  sass_dir: assets/css
  load_paths:
    - node_modules/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
